services:
  postgres-user:
    image: postgres:16
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - fraudshield-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-ingestion:
    image: postgres:16
    environment:
      POSTGRES_DB: ingestiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres-ingestion-data:/var/lib/postgresql/data
    networks:
      - fraudshield-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ingestiondb"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      postgres-user:
        condition: service_healthy
    networks:
      - fraudshield-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - user-service
    networks:
      - fraudshield-network

  ingestion-service:
    build: ./ingestion-service
    ports:
      - "8082:8082"
    depends_on:
      - api-gateway
    networks:
      - fraudshield-network

volumes:
  postgres-user-data:
  postgres-ingestion-data:

networks:
  fraudshield-network:
    driver: bridge
